### Atelier Pandas

##### Contexte 
Une entreprise possède plusieurs bâtiments équipés de capteurs IoT. 
Chaque capteur collecte régulièrement des informations sur la température, l'humidité, la pression, 
la consommation énergétique, l'état du capteur, le bâtiment, la date et l'heure de la mesure. 
Les données doivent être préparées et analysées avant d'être transmises à un futur système de 
Machine Learning permettant de détecter des situations anormales.

##### Structuration du projet
        1) Structuration le projet 
        2) Stocker le fichier fourni mesures_capteurs.csv dans le sous-dossier data 
        3) Créer le notebook atelier_pandas_iot.ipynb

In [19]:
import pandas as pd

#### Partie 1 – Series

##### 1) Création d'une Series contenant 4 températures

In [20]:
serie_temp4 = pd.Series([12.25, 38.01, 5.8, 14.5])
serie_temp4

0    12.25
1    38.01
2     5.80
3    14.50
dtype: float64

##### 2) Affichage de l'index de la série

In [21]:
print("L'index de la séerie : ",serie_temp4.index)

L'index de la séerie :  RangeIndex(start=0, stop=4, step=1)

##### 3) Affichage de la 1ère valeur de la série

In [22]:
print("La 1ére valeur de la série est : ", serie_temp4[0])

La 1ére valeur de la série est :  12.25

##### 4) Affichage de la dernière valeur de la série

In [23]:
print("La dernière valeur de la série est : ", serie_temp4.iloc[-1])

La dernière valeur de la série est :  14.5

##### 5) Création de deux façon différentes, une Series de 4 températures avec comme index les heures de mesure 12h, 13h, 14h et 15h

In [ ]:
# Première maniére
serie_temp_h = pd.Series([21.5, 32, 7.03, 18], index=['12h', '13h', '14h', '15h'])

# Deuxiéme manière
dict = {'12h' : 21.5, '13h' : 32, '15h' : 7.03, '15h' : 18}
serie_temp_h = pd.Series(dict)
serie_temp_h

12h    21.5
13h    32.0
15h    18.0
dtype: float64

##### 6) Affichage la 1ère et la dernière valeur

In [34]:
# 1e valeur
print("La 1ére valeur de la série est : ", serie_temp_h['12h'])

# dernière valeur
print("La dernière valeur de la série est : ", serie_temp_h.iloc[-1])

La 1ére valeur de la série est :  21.5
La dernière valeur de la série est :  18.0

#### Partie 2 – DataFrame

##### 1) Création et affichage du dataframe df_test à partir du dictionnaire suivant

In [36]:
# Création du dictionnaire df_test
data = { 
    "capteur": ["C001", "C002", "C003"], 
    "temperature": [24.5, 25.1, 26.3], 
    "humidite": [65, 67, 70] 
}

In [38]:
# Création et affichagedu DataFrame à partir du dictionnaire data
df_test = pd.DataFrame(data)
df_test

  capteur  temperature  humidite
0    C001         24.5        65
1    C002         25.1        67
2    C003         26.3        70

##### 2) Importation du dataset mesures_capteurs.csv dans le dataframe df

In [53]:
df = pd.read_csv(r'C:\Users\cissc\OneDrive\Documents\P1IA_ODC\atelier_pandas\data\mesures_capteurs.csv')
# On ajoute un 'r' devant les guillemets pour éviter les erreurs de caractères)

##### 3) Affichage les dimensions de df

In [55]:
print("Les dimensions : ", df.shape)

Les dimensions :  (605, 9)

NB : Dans la suite de l’atelier, on travaillera avec le dataframe df

#### Partie 3 – Exploration

##### 1) Affichage des premières lignes

In [57]:
df.head()

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK